/**
 * Reference: https://github.com/obsidianmd/obsidian-sample-plugin/blob/master/esbuild.config.mjs
 */

import process from 'node:process';

import builtins from 'builtin-modules';
import esbuild from 'esbuild';

const prod = process.argv[2] === 'production';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins,
	],
	format: 'cjs',
	target: 'es2018',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: process.env.OUTPUT ?? 'main.js',
	minify: prod,
	loader: {
		'.svg': 'text',
	},
	define: {
		// Remove inline Vitest code
		'import.meta.vitest': 'undefined',
		// Embed obfuscation token
		'process.env.SETTINGS_OBFUSCATE_KEY':
			`"${process.env.SETTINGS_OBFUSCATE_KEY}"` || '"secret"',
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
